# 第7章 アンサンブル
## 7.3 スタッキング
### 7.3.3 スタッキングの実装

In [4]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer

cancer=load_breast_cancer()
X=pd.DataFrame(cancer.data)
y=pd.DataFrame(cancer.target)

In [5]:
from sklearn.model_selection import train_test_split

train_x,test_x,train_y,test_y=train_test_split(X,y)

# 学習データを学習データとバリデーションデータに分ける
from sklearn.model_selection import KFold

kf = KFold(n_splits=4, shuffle=True, random_state=71)
tr_idx, va_idx = list(kf.split(train_x))[0]
tr_x, va_x = train_x.iloc[tr_idx], train_x.iloc[va_idx]
tr_y, va_y = train_y.iloc[tr_idx], train_y.iloc[va_idx]

In [22]:
kf=KFold(n_splits=4, shuffle=True, random_state=71)
idxs=[]
idxs.append(list(kf.split(train_x))[0][1])
idxs.append(list(kf.split(train_x))[1][1])
idxs.append(list(kf.split(train_x))[2][1])
idxs.append(list(kf.split(train_x))[3][1])
idxs

[array([  3,   4,   6,  15,  20,  22,  24,  26,  31,  34,  35,  44,  46,
         53,  59,  62,  63,  64,  68,  85,  88,  91,  94,  98, 104, 105,
        106, 110, 114, 122, 124, 127, 130, 137, 139, 141, 142, 148, 150,
        161, 162, 172, 173, 174, 180, 182, 191, 196, 202, 203, 212, 213,
        222, 224, 227, 228, 229, 231, 232, 233, 242, 244, 245, 247, 248,
        251, 252, 255, 263, 267, 270, 276, 284, 286, 287, 290, 294, 298,
        302, 303, 306, 309, 316, 321, 323, 324, 328, 333, 334, 345, 346,
        352, 357, 361, 364, 385, 389, 396, 397, 402, 403, 411, 415, 417,
        420, 421, 423]),
 array([  5,   7,   9,  17,  28,  29,  48,  49,  50,  57,  61,  65,  69,
         71,  78,  81,  83,  92,  95,  97, 102, 108, 109, 115, 116, 119,
        129, 132, 136, 143, 146, 147, 151, 152, 157, 158, 159, 160, 164,
        166, 167, 169, 184, 187, 188, 190, 195, 199, 200, 201, 204, 205,
        209, 210, 214, 215, 216, 218, 226, 230, 234, 235, 236, 243, 249,
        256, 259, 261, 266

In [23]:
np.concatenate(idxs)

array([  3,   4,   6,  15,  20,  22,  24,  26,  31,  34,  35,  44,  46,
        53,  59,  62,  63,  64,  68,  85,  88,  91,  94,  98, 104, 105,
       106, 110, 114, 122, 124, 127, 130, 137, 139, 141, 142, 148, 150,
       161, 162, 172, 173, 174, 180, 182, 191, 196, 202, 203, 212, 213,
       222, 224, 227, 228, 229, 231, 232, 233, 242, 244, 245, 247, 248,
       251, 252, 255, 263, 267, 270, 276, 284, 286, 287, 290, 294, 298,
       302, 303, 306, 309, 316, 321, 323, 324, 328, 333, 334, 345, 346,
       352, 357, 361, 364, 385, 389, 396, 397, 402, 403, 411, 415, 417,
       420, 421, 423,   5,   7,   9,  17,  28,  29,  48,  49,  50,  57,
        61,  65,  69,  71,  78,  81,  83,  92,  95,  97, 102, 108, 109,
       115, 116, 119, 129, 132, 136, 143, 146, 147, 151, 152, 157, 158,
       159, 160, 164, 166, 167, 169, 184, 187, 188, 190, 195, 199, 200,
       201, 204, 205, 209, 210, 214, 215, 216, 218, 226, 230, 234, 235,
       236, 243, 249, 256, 259, 261, 266, 269, 272, 277, 279, 28

In [24]:
np.argsort(np.concatenate(idxs))

array([320, 214, 321,   0,   1, 107,   2, 108, 322, 109, 323, 324, 215,
       325, 326,   3, 327, 110, 328, 216,   4, 329,   5, 330,   6, 217,
         7, 218, 111, 112, 331,   8, 219, 332,   9,  10, 220, 221, 222,
       223, 333, 224, 225, 226,  11, 334,  12, 227, 113, 114, 115, 335,
       228,  13, 336, 337, 229, 116, 230,  14, 231, 117,  15,  16,  17,
       118, 338, 339,  18, 119, 232, 120, 340, 233, 341, 234, 235, 236,
       121, 342, 237, 122, 343, 123, 344,  19, 238, 239,  20, 240, 241,
        21, 124, 345,  22, 125, 346, 126,  23, 347, 242, 348, 127, 243,
        24,  25,  26, 349, 128, 129,  27, 350, 351, 244,  28, 130, 131,
       245, 352, 132, 246, 247,  29, 248,  30, 249, 250,  31, 353, 133,
        32, 251, 134, 252, 253, 254, 135,  33, 255,  34, 354,  35,  36,
       136, 256, 257, 137, 138,  37, 258,  38, 139, 140, 259, 260, 355,
       261, 141, 142, 143, 144,  39,  40, 262, 145, 263, 146, 147, 356,
       148, 357, 358,  41,  42,  43, 359, 360, 264, 265, 361,  4